# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubri" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "cb5cc38c91c8fb1fe14e91285d334b5097810601a2117f64aabbc82d1328a166"
      url "https://github.com/kubri/kubri/releases/download/v#{version}/kubri_#{version}_MacOS_x86_64.tar.gz",
        verified: "github.com/kubri/kubri/"
    end
    on_arm do
      sha256 "56d58f164bb9c9a00c8077165b4b39f2bbcdaa61b4d81ad1f0d234aae573b19f"
      url "https://github.com/kubri/kubri/releases/download/v#{version}/kubri_#{version}_MacOS_arm64.tar.gz",
        verified: "github.com/kubri/kubri/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7c778f713423bbad033bda6c20b9c85d6163761afe8516e27732870568bdc9a9"
      url "https://github.com/kubri/kubri/releases/download/v#{version}/kubri_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/kubri/kubri/"
    end
    on_arm do
      sha256 "e865ee0a16674cd38ac987472f4b748df5e54d70efd458a4b7f178fa1d4defa7"
      url "https://github.com/kubri/kubri/releases/download/v#{version}/kubri_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/kubri/kubri/"
    end
  end

  name "kubri"
  desc "Kubri signs and releases software for common package managers and software update frameworks."
  homepage "https://kubri.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubri"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubri"]
    end
  end

  # No zap stanza required

end
