# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubri < Formula
  desc "Kubri signs and releases software for common package managers and software update frameworks."
  homepage "https://kubri.dev/"
  version "0.5.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kubri/kubri/releases/download/v0.5.1/kubri_0.5.1_MacOS_x86_64.tar.gz"
      sha256 "0213752bd2325c2be923405b1c6b7ff1f03c3afa98f027c7c3995701291e5c8a"

      def install
        bin.install "kubri"
      end
    end
    on_arm do
      url "https://github.com/kubri/kubri/releases/download/v0.5.1/kubri_0.5.1_MacOS_arm64.tar.gz"
      sha256 "2dd4d22b98276e6d269156baf217231698514ad8df8b244cb7263a7998eb8158"

      def install
        bin.install "kubri"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubri/kubri/releases/download/v0.5.1/kubri_0.5.1_Linux_x86_64.tar.gz"
        sha256 "581826db33ad25bdadd13a973e2cb7da6ffbd3eba90fea2c11ea1612e7f13e00"

        def install
          bin.install "kubri"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kubri/kubri/releases/download/v0.5.1/kubri_0.5.1_Linux_armv6.tar.gz"
        sha256 "299c84cd4c364e6b651aa450271223e0eba67a4c4929274f451527b8062af702"

        def install
          bin.install "kubri"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubri/kubri/releases/download/v0.5.1/kubri_0.5.1_Linux_arm64.tar.gz"
        sha256 "c5e660e5ab2bb9221782b0bc12baeae2b9068cdb482b93f936d3b40829bd0bed"

        def install
          bin.install "kubri"
        end
      end
    end
  end

  test do
    system "#{bin}/kubri version"
  end
end
