# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubri < Formula
  desc "Kubri signs and releases software for common package managers and software update frameworks."
  homepage "https://kubri.dev/"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubri/kubri/releases/download/v0.7.1/kubri_0.7.1_MacOS_x86_64.tar.gz"
      sha256 "4fe646929db250981aadbe2507a68a7a5823f5e74c52878ce4df3d42a56cd03a"

      def install
        bin.install "kubri"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubri/kubri/releases/download/v0.7.1/kubri_0.7.1_MacOS_arm64.tar.gz"
      sha256 "af270fec1c7aaf8eafde502dcd8cec046a59f416203befd1e92215a1c9aaca8d"

      def install
        bin.install "kubri"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubri/kubri/releases/download/v0.7.1/kubri_0.7.1_Linux_x86_64.tar.gz"
      sha256 "bd7ce32a5aea870d5fb0147c53f15a7d0dfeaf6a2b2d09b6542df330c748bc28"
      def install
        bin.install "kubri"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kubri/kubri/releases/download/v0.7.1/kubri_0.7.1_Linux_armv6.tar.gz"
      sha256 "f2abdbd0fed937af067c22ff49cd4edbaf5f65c3e352619bb6c097d67827d00d"
      def install
        bin.install "kubri"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubri/kubri/releases/download/v0.7.1/kubri_0.7.1_Linux_arm64.tar.gz"
      sha256 "1cf9a820e35d955297d1dc8583e1c3839a36309768168e8ad82a7169d8a386a6"
      def install
        bin.install "kubri"
      end
    end
  end

  test do
    system "#{bin}/kubri version"
  end
end
