# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubri < Formula
  desc "Kubri signs and releases software for common package managers and software update frameworks."
  homepage "https://kubri.dev/"
  version "0.5.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kubri/kubri/releases/download/v0.5.2/kubri_0.5.2_MacOS_x86_64.tar.gz"
      sha256 "1ba622cd889ca0282bf58f88358c657303a97905303835e7e6c164a3e583e449"

      def install
        bin.install "kubri"
      end
    end
    on_arm do
      url "https://github.com/kubri/kubri/releases/download/v0.5.2/kubri_0.5.2_MacOS_arm64.tar.gz"
      sha256 "850cde0a6b226970d05ce85c764d93ebbcb3b119ead771169a031302a377e29f"

      def install
        bin.install "kubri"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubri/kubri/releases/download/v0.5.2/kubri_0.5.2_Linux_x86_64.tar.gz"
        sha256 "3ee52d36629a803672bb849c42c4ae5c0daa315abe219a66474291eb2c5f257a"

        def install
          bin.install "kubri"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kubri/kubri/releases/download/v0.5.2/kubri_0.5.2_Linux_armv6.tar.gz"
        sha256 "c0d13d28ac70a95c17e05fe290147603edec1b6f9ec11457839f992cf5cd9627"

        def install
          bin.install "kubri"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubri/kubri/releases/download/v0.5.2/kubri_0.5.2_Linux_arm64.tar.gz"
        sha256 "3ff55ef40f1dd01ef7df836339723ab8009b4ae2c5fdb9a6086634335ee12fed"

        def install
          bin.install "kubri"
        end
      end
    end
  end

  test do
    system "#{bin}/kubri version"
  end
end
